/**
 * Critical journey: Login → create ticket using pre-seeded category →
 * verify in list and detail → logout.
 *
 * Why this journey:
 * - Ticket creation requires a published workflow, which the seed creates.
 * - The ticket must appear in the index and open to its detail page,
 *   covering the ticket-management and ticket-workflow-execution specs.
 *
 * The seed creates:
 *   - Root user "Alice Admin" (alice@example.com / SuperSecret42!)
 *   - Category "General" with a published workflow
 *   - Desk "General Support"
 */

import { test, expect } from "@playwright/test";
import { startServer, stopServer, activeServer } from "../server-lifecycle.js";

function base(): string {
  if (!activeServer) throw new Error("server not started");
  return activeServer.baseURL;
}

test.describe("Ticket Lifecycle", () => {
  test.beforeAll(async () => {
    await startServer({ seed: true });
  });

  test.afterAll(async () => {
    await stopServer();
  });

  test("create ticket, verify in list, detail, and navigate from index", async ({ page }) => {
    // ── Login ─────────────────────────────────────────────────────────
    await page.goto(base() + "/login");
    await expect(page.getByLabel(/email/i)).toBeVisible();
    await page.getByLabel(/email/i).fill("alice@example.com");
    await page.getByLabel(/password/i).fill("SuperSecret42!");
    await page.getByRole("button", { name: /log in|sign in/i }).click();
    await expect(page).toHaveURL(/\/tickets/);

    // ── Create ticket ─────────────────────────────────────────────────
    await page.goto(base() + "/tickets/new");
    await expect(page.locator("h2")).toHaveText(/ticket details/i);

    const title = "Login issue " + Date.now();
    await page.getByLabel(/title/i).fill(title);
    await page.getByLabel(/description/i).fill("Cannot log in");

    // The seeded "General" category has a published workflow
    await page.getByLabel(/category/i).selectOption({ label: "General" });
    await page.getByLabel(/priority/i).selectOption("high");
    await page.getByRole("button", { name: /create ticket/i }).click();

    // After creation, the server redirects to the ticket detail page
    await expect(page.getByText(title)).toBeVisible({ timeout: 5000 });

    // Verify priority is shown (using accessible locators)
    await expect(page.getByRole("cell", { name: "High" })).toBeVisible();

    // Verify exact status "New" on the detail page
    await expect(page.getByText("New").first()).toBeVisible();

    // Capture the actual ticket number generated by the system
    const ticketNumberText = await page.getByText(/TKT-\d+/).textContent();
    expect(ticketNumberText).not.toBeNull();
    expect(ticketNumberText).toMatch(/TKT-\d+/);

    // ── Verify ticket in the index ────────────────────────────────────
    await page.goto(base() + "/tickets");
    await expect(page.getByText(title)).toBeVisible({ timeout: 5000 });

    // ── Open ticket detail from index ─────────────────────────────────
    await page.getByText(title).first().click();
    await page.waitForURL(/\/tickets\/\d+/);

    // Verify the dynamically generated ticket number appears on detail
    await expect(page.getByText(ticketNumberText!)).toBeVisible();
  });

  test("logout and auth gate redirects unauthenticated to login", async ({ page }) => {
    await page.goto(base() + "/login");
    await page.getByLabel(/email/i).fill("alice@example.com");
    await page.getByLabel(/password/i).fill("SuperSecret42!");
    await page.getByRole("button", { name: /log in|sign in/i }).click();
    await expect(page).toHaveURL(/\/tickets/);

    const logoutBtn = page.getByRole("button", { name: /log out|sign out/i });
    await expect(logoutBtn).toBeVisible();
    await logoutBtn.click();
    await expect(page).toHaveURL(/\/login/, { timeout: 5000 });

    // Verify auth gate: /tickets redirects to /login after logout
    await page.goto(base() + "/tickets");
    await expect(page).toHaveURL(/\/login/);
  });
});